##---
# Source: weave-cloud/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: weave-cloud
  labels:
    app: weave-cloud
    chart: weave-cloud-0.3.0
    release: weave-cloud
    heritage: Tiller
rules:
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - '*'
  - nonResourceURLs:
      - '*'
    verbs:
      - '*'
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: weave-cloud
  labels:
    app: weave-cloud
    chart: weave-cloud-0.3.0
    release: weave-cloud
    heritage: Tiller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: weave-cloud
subjects:
  - name: weave-cloud
    namespace: "weave"
    kind: ServiceAccount